export let roadMapData = [
  {
    1: [
      "WEB NOVEL LAUNCHING (STORY DEVELOPMENT OF HEROEZ! | Heroes in 6th Dimension)",
      "OFFICIAL WEBSITE LAUNCH",
      "ANIME TRAILER",
      "ESPORTS TRAILER",
      "MINTING OF 3333 HEROES ON ETHEREUM CHAIN",
      "REVEAL PHASE",
    ],
    2: [
      "MANGA/WEBNOVEL DEVELOPMENT",
      "STAKING",
      "ESTABLISHING HZ ESPORTS TEAM",
      "BRAND MERCH LAUNCH",
      "STUDIO Z DEVELOPMENT",
      "WEB 3 NFT MARKETING AGENCY",
    ],
    3: [
      "GAMIFICATIONS",
      "STUDIO Z STABILIZATION OF OPERATIONS",
      "ASSET MANAGEMENT COMPANY",
    ],
  },
];
